# Generated by Django 2.2.3 on 2019-07-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('familleProduit', models.CharField(max_length=200)),
                ('descriptionProduit', models.CharField(max_length=200)),
                ('quantiteMin', models.PositiveIntegerField()),
                ('packaging', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
    ]
