# Generated by Django 2.2.7 on 2019-11-22 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_auto_20191017_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='article',
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vente',
            name='modePaiement',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='pointsFidelite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vente',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArticleVendu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('prixAvant', models.IntegerField(null=True)),
                ('prixApres', models.IntegerField(null=True)),
                ('promo', models.IntegerField(null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoapp.Produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoapp.Vente')),
            ],
        ),
        migrations.AddField(
            model_name='vente',
            name='articles',
            field=models.ManyToManyField(through='djangoapp.ArticleVendu', to='djangoapp.Produit'),
        ),
    ]
