# Generated by Django 2.2.7 on 2019-12-02 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20191122_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('prixAvant', models.IntegerField(default=0)),
                ('prixApres', models.IntegerField(default=0)),
                ('promo', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTicket', models.DateField(blank=True, null=True)),
                ('Prix', models.IntegerField(default=0)),
                ('Client', models.TextField()),
                ('PointsFidelite', models.IntegerField(default=0)),
                ('ModePaiement', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='vente',
            name='articles',
        ),
        migrations.DeleteModel(
            name='ArticleVendu',
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
        migrations.AddField(
            model_name='purchasedarticle',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_articles', to='djangoapp.Ticket'),
        ),
    ]
