# Generated by Django 3.0 on 2019-12-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMagasin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('codeProduit', models.CharField(max_length=200)),
                ('numeroFournisseur', models.IntegerField()),
                ('codeFournisseur', models.CharField(max_length=200)),
                ('stockDisponible', models.IntegerField()),
            ],
        ),
    ]
