# Generated by Django 3.0.1 on 2019-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_deliveredproduct_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Paiement',
            new_name='Montant',
        ),
        migrations.AlterField(
            model_name='customer',
            name='carteFid',
            field=models.CharField(max_length=200),
        ),
    ]
