# Generated by Gobrunk on 2020-01-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_auto_20191220_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('date',  models.DateField(blank=True, null=True)),
            ],
        ),
    ]
