# Generated by Django 3.0.3 on 2020-02-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_auto_20200203_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Credit',
            field=models.IntegerField(default=0),
        ),
    ]
