# Generated by Django 3.0.3 on 2020-02-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0015_auto_20200203_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFacture', models.CharField(max_length=200)),
                ('dateFacture', models.DateTimeField(blank=True, null=True)),
                ('datePaiement', models.DateTimeField(blank=True, null=True)),
                ('numeroCommande', models.CharField(max_length=200)),
                ('dateLivraison', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('prix', models.IntegerField(default=0)),
                ('quantite', models.IntegerField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture_item', to='djangoapp.Facture')),
            ],
        ),
    ]
