# Generated by Django 3.0.3 on 2020-02-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_facture_factureitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='dateFacture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='dateLivraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='datePaiement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
