# Generated by Django 3.0.3 on 2020-02-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0017_auto_20200203_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedarticle',
            name='promo_client_produit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='Promo_client',
            field=models.IntegerField(default=0),
        ),
    ]
