# Generated by Django 3.0.3 on 2020-02-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0018_auto_20200204_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='PanierMoyen',
            field=models.IntegerField(default=0),
        ),
    ]
